// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"encoding/json"
	"time"
)

type CabLocation struct {
	ID        int64       `json:"id"`
	Driver    int64       `json:"driver"`
	CellID    string      `json:"cell_id"`
	Position  interface{} `json:"position"`
	Available bool        `json:"available"`
	CreatedAt *time.Time  `json:"created_at"`
	UpdatedAt *time.Time  `json:"updated_at"`
}

type Driver struct {
	ID             int64   `json:"id"`
	Name           string  `json:"name"`
	Email          string  `json:"email"`
	HashedPassword string  `json:"hashed_password"`
	Contact        string  `json:"contact"`
	CarNumber      string  `json:"car_number"`
	CarBrand       string  `json:"car_brand"`
	CarColor       string  `json:"car_color"`
	ProfilePicture *string `json:"profile_picture"`
}

type PaymentHistory struct {
	ID            int64     `json:"id"`
	AmountCents   int32     `json:"amount_cents"`
	PaymentMethod string    `json:"payment_method"`
	CreatedAt     time.Time `json:"created_at"`
}

type PendingRide struct {
	ID                  int64           `json:"id"`
	UserID              string          `json:"user_id"`
	DriverID            int64           `json:"driver_id"`
	Source              interface{}     `json:"source"`
	Destination         json.RawMessage `json:"destination"`
	CreatedAt           time.Time       `json:"created_at"`
	EstimatedPriceCents int32           `json:"estimated_price_cents"`
}

type RideHistory struct {
	ID          int64       `json:"id"`
	Source      interface{} `json:"source"`
	Destination interface{} `json:"destination"`
	User        string      `json:"user"`
	PaymentID   *int64      `json:"payment_id"`
	Driver      int64       `json:"driver"`
	BoardTime   time.Time   `json:"board_time"`
	ArrivalTime *time.Time  `json:"arrival_time"`
	Status      string      `json:"status"`
}

type UserMetaData struct {
	ID          string    `json:"id"`
	PhoneNumber string    `json:"phone_number"`
	DateOfBirth time.Time `json:"date_of_birth"`
	CreatedDate time.Time `json:"created_date"`
}
