package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.27

import (
	"context"
	"fmt"

	db "github.com/ghost-codes/uber/db/sqlc"
	"github.com/ghost-codes/uber/graph/model"
)

// CreateDriver is the resolver for the createDriver field.
func (r *mutationResolver) CreateDriver(ctx context.Context, data model.CreateUserData) (*db.Driver, error) {
	panic(fmt.Errorf("not implemented: CreateDriver - createDriver"))
}

// FetchDriver is the resolver for the fetchDriver field.
func (r *queryResolver) FetchDriver(ctx context.Context, id string) (*db.Driver, error) {
	panic(fmt.Errorf("not implemented: FetchDriver - fetchDriver"))
}
